default: &default
  adapter: mysql2
  encoding: utf8
  database: heroku_f253ae219ba652c
  username: bb57d9f10836a2
  password: 33d88d2c
  host: us-cdbr-iron-east-01.cleardb.net
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  database: heroku_f253ae219ba652c
  username: bb57d9f10836a2
  password: 33d88d2c
  host: us-cdbr-iron-east-01.cleardb.net
  port: 3306

test:
  <<: *default
  database: database-academy_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>